---

- name: install fisherman
  block:
    - name: create directory
      file:
        name: "{{ fish_config_dir }}/functions/"
        state: directory

    - name: install fisherman
      get_url:
        url: https://git.io/fisher
        dest: "{{ fish_config_dir }}/functions/fisher.fish"

- name: install fisherman packages by fishfile
  block:
    - name: set fishfile
      copy:
        src: "{{ role_path }}/files/fisherman/fishfile"
        dest: "{{ fish_config_dir }}/fishfile"
      register: fishfile

    - name: install fisherman packages
      when: fishfile.changed
      shell: fisher
      args:
        executable: /usr/bin/fish
      register: fisher
      changed_when: "'Installing' in fisher.stdout"
