---

- name: install fish by apt
  when: ansible_pkg_mgr == "apt"
  become: yes
  block:
  - name: add fish v2 PPA
    apt_repository:
      repo: ppa:fish-shell/release-2

  - name: install fish by apt
    apt:
      name: fish
      update_cache: yes
      cache_valid_time: 3600

- name: install fish
  become: yes
  package:
    name: fish

- name: copy config files
  synchronize:
    src: "{{ role_path }}/files/fish/"
    dest: "{{ fish_config_dir }}"

- name: install fisherman packages
  import_tasks: fisher.yml

- name: ensure fish config file exists
  copy:
    content: ""
    dest: "{{ fish_config_dir }}/config.fish"
    force: no

- name: enable triggered functions
  lineinfile:
    path: "{{ fish_config_dir }}/config.fish"
    line: ls_on_cd

- name: enable Vim+Emacs mode
  lineinfile:
    path: "{{ fish_config_dir }}/config.fish"
    line: "{{ item.line }}"
  loop:
    - line: '# enable Vim+Emacs mode'
    - line: fish_hybrid_key_bindings
